### PR TITLE
Feature/db manager

### PR DESCRIPTION
**Pull request by jrdbuch**

### CODE REVIEW

**Comment by msmart14** [comment]
This looks good to me but it would be good to get feedback from someone with more experience/knowledge about sqllite, best practices for error handling, best practices for testing, etc. Just to be clear -- the test aren't hitting the actual db, right? Or did I misread that.

**Comment by jrdbuch** [comment]
> Just to be clear -- the test aren't hitting the actual db, right? Or did I misread that.

Correct, the test db is an in-memory sqllite db

**Comment by jrdbuch** [comment]
I need to add session.commit(), date filtering to get_activities

**Review by tschelbs18 — APPROVED** [review]
Nice work

**Pull request merged**
